defaults:
  - model: qwen
  - dataset: toy_dataset_100
  - search: default
  - _self_

resources:
  global_llm_concurrency: 500
  global_gpu_concurrency: 1


search:
  query_concurrency: 16
  subquery_concurrency: 4
  llm_concurrency: 100

evaluation:
  llm_judge_concurrency: 32

storage:
  path: ${hydra:runtime.cwd}/storage/${dataset.name}
  force_rebuild_ontology: false

output_dir: ${hydra:runtime.cwd}/outputs/${dataset.name}
